const sampleListing = [
    
    {
        brand: "MAC",
        image: "https://images.unsplash.com/photo-1625093742435-6fa192b6fb10?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bGlwc3RpY2t8ZW58MHx8MHx8fDA%3D",
        about_product: "A plumping gloss stick that nourishes and conditions lips with translucent colour and non-sticky shine.",
        shade: "Creamy",
        type: "Liquid Shinning",
    },
    {
        brand: "Maybelline",
        about_product: "Maybelline Color Sensational Lipstick, Lip Makeup, Cream Finish, Hydrating Lipstick",
        image:"https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/71pdtdPLdOL._SL1500_.jpg",
        shade: "On The Mauve",
        type: "Liquid",
    },
    {
        brand: "L'Oreal",
        about_product: "L'Oreal Paris Colour Riche Lipstick offers luxurious, rich color with a creamy texture.",
        image:"https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/616nN33YlAL._SL1500_.jpg",
        shade: "Rosewood",
        type: "Cream",
    },
    
    {
        brand: "Bite Beauty",
        about_product: "Amuse Bouche Lipstick is made with natural and organic ingredients, delivering bold color and creamy texture.",
        image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcT1TOz0DTroNRcsTq0ZMAzah_IkJwxCpt8sMjeMM2ZphI3WcPoPAMKQPrWWl7vpCVrFyG4KWs_sttHX1W9544oNvP0m29NeuT0SkekTE4Y4BuKo0MX82YViGw",
        shade: "#2020 (Light Brown Mauvey Nude)",
        type: "Creamy Matte",
    },
    
    {
        brand: "Maybelline",
        about_product:"Maybelline Color Sensational Ultimatte Matte Lipstick, Non-Drying, Intense Color Pigment, More Taupe, Rose Nude",
        image:"https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/71LizDnRdXL._SL1500_.jpg",
        shade: "Rose Nude",
        type: "Nude",
    },
    
    {
        brand: "Fenty Beauty",
        image: "https://www.sephora.com/productimages/sku/s2708063-main-zoom.jpg?imwidth=1224",
        about_product: "Mattemoiselle Plush Matte Lipstick features a weightless, long-wearing formula with intense color payoff.",
        shade: " Nude Venus - neutral coral nude",
        type: "Matte",
    },
    {
        brand: "Huda Beauty",
        about_product:"HUDA BEAUTY Power Bullet Matte Lipstick - Throwback Collection Game Night",
        image:" https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/41v09KHOQBL.jpg",
        shade:"Brown",
        type: "Matte",
    },
    {
        brand: "Pat McGrath Labs",
        about_product: "MatteTrance Lipstick provides rich, velvety color in a luxurious matte finish.",
        image:"https://www.patmcgrath.com/cdn/shop/files/PMG_LIP_LIMITED_EDITION_GOLD_HEART_MATTETRANCE_PDP_ELSON_CLOSED.jpg?v=1700541373&width=1100",
        shade: "Red",
        type: "Matte",
    },
    
    {
        brand: "wet n wild",
        about_product: "wet n wild Silk Finish Lipstick| Hydrating Lip Color| Rich Buildable Color| Will You Be With Me? Pink, 0.13 Ounce",
        image: "https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/71ja2hmrz3L._SX679_.jpg",
        shade: "Pink",
        type: "Matte",
    },
    {
        brand: "3ina",
        about_product:"3ina MAKEUP - Vegan - Cruelty Free - The Lipstick 265 - Brown Lipstick - 5h Lasting Lipstick - Highly Pigmented - Matte - Vanilla Scented - Lipstick with Magnetic Cap",
        image:"https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/51RtaAHolML._SL1500_.jpg",
        shade: "265 - Brown ",
        type: "Lipstick",
    },
    {
        brand: "Fenty Beauty ",
        about_product:"Fenty Beauty by Rihanna Gloss Bomb Universal Lip Luminizer - Riri",
        image:"https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/51bwEhtf3GL.jpg",
        shade: "Riri",
        type: "Liquid",
    },
    {
        brand: "L’Oréal Paris ",
        about_product:"L’Oréal Paris Infallible Matte Resistance Liquid Lipstick, up to 16 Hour Wear, Pay Day 560, 0.17 Fl Oz",
        image:"https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/61b264jiD-L._SL1500_.jpg ",
        shade:"Pay Day",
        type: " Matte",
    },
    {
        brand: "Revlon ",
        about_product:"Revlon Lipstick, ColorStay Suede Ink, Built-in Primer, Infused with Vitamin E, Waterproof, Smudge-proof, Matte Color, 007 Feed the Flame, 0.09 oz.",
        image:"https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/81waXnYLUPL._SL1500_.jpg ",
        shade:"FEED THE FLAME",
        type: " Matte",
    },
    {
        brand: "COVERGIRL",
        about_product:"COVERGIRL Continuous Color Lipstick It's Your Mauve 030, 0.13 oz (packaging may vary).",
        image:"https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/51nn6W45bhL._SL1500_.jpg",
        shade:" It's Your Mauve 030",
        type: "Balm",
    },
    {
        brand: "NYX PROFESSIONAL MAKEUP",
        about_product:"NYX PROFESSIONAL MAKEUP Shout Loud Satin Lipstick, Infused With Shea Butter - Opinionated (Warm Burgundy)",
        image:"https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/61XH7o+yITL._SL1500_.jpg ",
        shade:"Opinionated",
        type: " Matte",
    },
    {
        brand: "LAURA GELLER NEW YORK",
        about_product:"LAURA GELLER NEW YORK Italian Marble Sheer Lipstick - Strawberry Toffee - Hydrating & Lightweight - Vitamin E & Caster Seed Oil - Cream Finish",
        image:" https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/61sFbc0HkSL._SL1500_.jpg",
        shade:"06 Strawberry Toffee ",
        type: " Matte",
    },
    {
        brand: "L’Oréal Paris  ",
        about_product:"L’Oréal Paris Colour Riche Original Creamy, Hydrating Satin Lipstick with Argan Oil and Vitamin E, Ballerina Shoes ",
        image:" https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/51kn1OGPvpL._SL1024_.jpg",
        shade:"Ballerina Shoes",
        type: " Matte",
    },
   
    {
        brand:"Revlon ",
        about_product: "Revlon Lipstick, Super Lustrous Lipstick, Creamy Formula For Soft, Fuller-Looking Lips, Moisturized Feel, 778 Pink Promise, 0.15 oz",
        image:"https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/71VGvfyp+TL._SL1500_.jpg ",
        shade:" 778 Pink Promise",
        type:"Cream Solid ",
    },
    {
        brand:" Witch's Pouch",
        about_product: "Witch's Pouch Lovely Pink Lipstick for Women - Lustrous Lip Stick with Moisturizing Creamy Formula, High Impact Lip Color Hydrating Makeup Lipstick.",
        image:"https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/619tJOs0+BL._SL1500_.jpg ",
        shade:"S01 Lovely Pink ",
        type:"Cream ",
    },
    {
        brand:"DOGROT ",
        about_product: "Long-lasting Waterproof Lip Gloss for Daily Makeup Flesh Pink Shade, Non-Sticky, Non-Fading Lip Stain Ideal for Women, Girls. ",
        image:"https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/510fDkPSlYL._SL1000_.jpg ",
        shade:" Flesh Pink",
        type:" Matte",
    },
    {
        brand:"Revlon ",
        about_product: "Revlon Lipstick, ColorStay Suede Ink, Built-in Primer, Infused with Vitamin E, Waterproof, Smudge-proof, Matte Color. ",
        image:" https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/513d6GzIFkL._SL1000_.jpg",
        shade:"WANT IT ALL ",
        type:"Matte ",
    },
    {
        brand:" Shiseido",
        about_product: " Shiseido ModernMatte Powder Lipstick - Full-Coverage, Non-Drying Matte Lipstick - Weightless, Long-Lasting Color - 8-Hour Coverage",
        image:" https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/71-ECbLxQNL._SL1500_.jpg",
        shade:"Flame - 509 ",
        type:"Cream ",
    },
    {
        brand:"	GQ By Gloria Quinatana ",
        about_product: " Hydrating Lipstick, 24h Hydra Technology & Hyaluronic Acid for Soft Lips | Long-Lasting Lipstick, Intense Hydration | Lapiz Labial, Fragrance & Alcohol Free | Grace ",
        image:"https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/7122LTGclsL._SL1500_.jpg ",
        shade:" Grace",
        type:"	Matte ",
    },
    {
        brand:"KISS NEW YORK",
        about_product: " Smooth&Creamy Satin Finish, Long Lasting, Infused with Shea Butter and Vitamin E (Berry Rum)",
        image:" https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/6132Sd1OzKL._SL1500_.jpg",
        shade:" Berry Rum",
        type:"Satin ",
    },
    {
        brand:"Revlon ",
        about_product: "Revlon Lipstick, ColorStay Ultimate Suede Lipstick, High Impact Lip color with Moisturizing Creamy Formula, Infused with Vitamin E ",
        image:" https://m.media-amazon.com/images/W/MEDIAX_792452-T1/images/I/719oL-JsSpL._SX679_.jpg",
        shade:" Couture",
        type:" Matte",
    },

];
module.exports = { data: sampleListing };