const sampleFace = [
      {
        brand:"ORIGINAL PURE SERUM RADIANT",
        heading:"ORIGINAL PURE SERUM RADIANT NATURAL LIQUID FOUNDATION MINERAL SPF 20",
        img:"https://shop.bareminerals.com/cdn/shop/files/BM_SU23_OPSR_LightCool_2_Silo_2000x2000_R300.jpg?v=1690472051&width=1426",
        description:"Ultra-lightweight under-eye concealer that conceals, brightens, visibly depuffs. ",
        shade:"Light Cool 2 - very light cool skin with a pink hue",
        skin_type:"Dry Skin",
        price:500,
        size:"30 ml / 1.0 oz",
    },
    {
        brand:"bareMinerals",
        heading:"COMPLEXION RESCUE® BRIGHTENING UNDER EYE CONCEALER SPF 25",
        img:"https://shop.bareminerals.com/cdn/shop/products/1_BM_SU22_CRBC_PDP_WOW_sRGB.jpg?v=1677789623&width=1946",
        description:" Ultra-lightweight under-eye concealer that conceals, brightens, visibly depuffs.",
        shade:"Deep Sienna - For very deep cool skin with a red hue",
        skin_type:"Oily Skin",
        price:5300,
        size:"10 ml",
    },
    {
        brand:"bareMinerals ",
        heading:"ORIGINAL LIQUID MINERAL FOUNDATION BROAD SPECTRUM SPF 20 ",
        img:"https://shop.bareminerals.com/cdn/shop/products/94142.jpg?v=1675232218 ",
        description:"A clean, medium-coverage liquid foundation with SPF that visibly improves skin’s texture and reduces pore size over time.",
        shade:"Tan Nude -For medium-tan warm skin with a golden hue.",
        skin_type:"All Skin",
        price:5500,
        size:"30 ml / 1.0 oz",
    },
   
    {
        brand:"Maybelline Fit Me",
        heading:"Maybelline Fit Me Matte + Poreless Liquid Oil-Free Foundation Makeup, Classic Ivory, 1 Count (Packaging May Vary)",
        img:"https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/7141S1cZBlL._SL1500_.jpg ",
        description:" For a natural looking medium coverage liquid foundation makeup, look no further; In 40 shades, you'll find a fit for every skin tone; Best for normal to oily skin; refines pores for a natural looking matte finish ",
        shade:"	120 CLASSIC IVORY ",
        skin_type:"Dry Skin",
        price:3200,
        size:"30 ml / 1.0 oz",
    },
    {
        brand:"wet n wild ",
        heading:"wet n wild Photo Focus Matte Foundation Stick Makeup, Shell Ivory | Vegan & Cruelty-Free",
        img:"https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/7177qit-8kL._SL1500_.jpg ",
        description:"A panel of women were tested in a controlled environment simulating seven different lighting scenarios with professionally applied foundation, concealer and powder. ",
        shade:"	Shell Ivory ",
        skin_type:"All Skin",
        price:700,
        size:"20 ml / 1.0 oz",
    },
    {
        brand:" wet n wild  ",
        heading:" wet n wild Photo Focus Dewy Foundation, Toffee, 1.06 Ounces",
        img:"https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/615jmrzcgLL._SL1500_.jpg ",
        description:" ",
        shade:"Toffee ",
        skin_type:"Combination",
        price:500,
        size:"30 ml / 1.0 oz",
    },
    {
        brand:"COVER FX Power Play Foundation ",
        heading:"COVER FX Power Play Foundation - Shade M3 - Buildable Full Coverage - Waterproof Sweat-Proof Transfer-Proof - Natural Matte Finish - All Skin Types ",
        img:" https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/61BWCQl-nML._SL1500_.jpg",
        description:"The iconic bestselling clean beauty foundation that works (and plays) as hard as you do. Discover our buildable full-coverage formula and put your best face forward. ",
        shade:" Natural",
        skin_type:"Oily, Combination, Sensitive, Dry, Normal",
        price:5000,
        size:"30 ml / 1.0 oz",
    },
    {
        brand:"Build+Blend",
        heading:"Palladio BUILD + BLEND Foundation Stick, Contour Stick for Face, Professional Makeup for Perfect Look, 0.25 Ounce (Natural Beige) ",
        img:"https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/619XmI9f3XS._SL1500_.jpg ",
        description:" Achieve buildable medium coverage with this ultra-blendable creamy formula for a natural shine-free finish. Our comfortable, long wearing foundation promotes healthier, more supple skin with a powerful infusion of Hyaluronic acid and wont streak or settle into fine lines. ",
        shade:" Natural Beige",
        skin_type:"Oily Skin",
        price:800,
        size:"30 ml / 1.0 oz",
    },
    {
        brand:"Physicians Formula",
        heading:"Physicians Formula Butter Glow Concealer Light-to-Medium ",
        img:"https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/61G22i69FxL._SL1500_.jpg ",
        description:"This multi-use, radiance-boosting concealer delivers buildable flawless coverage and awakens skin to help you achieve flawless looks with a seamlessly radiant finish. ",
        shade:"Natural ",
        skin_type:"All Skin",
        price:820,
        size:"30 ml / 1.0 oz",
    },
];

module.exports = { data:sampleFace};